title: Play Rock Paper Scissors Game
description: A Ruby Programmed Rock Paper Scissors Game
show_downloads: true
google_analytics: false
theme: jekyll-theme-cayman # important
include:
  - index.md
  - how_to_run.md
  - Code.md
  - Comparing_Code.md
  - Testing.md
  - How_to_Build.md
  - about.md
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-cayman.gemspec
  - thumbnail.png
  - LICENSE
  - Copying.md
gems: 
  - github-pages
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
